classes: [plane, car, bird, cat, deer, dog, frog, horse, ship, truck]

lr: 0.0001

training_params:
  epoch_num: 15
  dataloader_params:
    batch_size: 64
    shuffle: true

eval_params:
  batch_size: 64
  shuffle: true


conv_layers:
  - name: Conv2d
    kwargs:
        in_channels: 3
        out_channels: 6
        kernel_size: 5
  - name: MaxPool2d
    kwargs:
        kernel_size: 2
        stride: 2
  - name: Conv2d
    kwargs:
        in_channels: 6
        out_channels: 16
        kernel_size: 5
  - name: MaxPool2d
    kwargs:
      kernel_size: 2
      stride: 2
fully-con_layers:
  - name: Linear
    kwargs:
        in_features: 400
        out_features: 120
  - name: Linear
    kwargs:
        in_features: 120
        out_features: 84
  - name: Linear
    kwargs:
        in_features: 84
        out_features: 10
