lr: 0.001

training_params:
  epoch_num: 10
  dataloader_params:
    batch_size: 64
    shuffle: true

eval_params:
  batch_size: 64
  shuffle: true


conv_layers:
  - name: Conv1d
    kwargs:
      in_channels: 1
      out_channels: 4
      kernel_size: 3
      padding: 1
  - name: Conv1d
    kwargs:
      in_channels: 4
      out_channels: 8
      kernel_size: 3
      padding: 1
      
fullycon_layers:
  - name: Linear
    kwargs:
        in_features: 240
        out_features: 64
  - name: Linear
    kwargs:
        in_features: 64
        out_features: 1