lr: 0.01

training_params:
  epoch_num: 200
  dataloader_params:
    batch_size: 64
    shuffle: false
  
eval_params: 
  batch_size: 64
  shuffle: false


layers:
  - name: Linear
    args: [240, 500]
  - name: Linear
    args: [500, 1]
