lr: 0.001

training_params:
  epoch_num: 200
  dataloader_params:
    batch_size: 64
    shuffle: true
  
eval_params: 
  batch_size: 64
  shuffle: true


layers:
  - name: Linear
    args: [160, 800]
  - name: Linear
    args: [800, 100]
  - name: Linear
    args: [100, 1]