


model:
  class: CNN
  kwargs:
    layers:
      - name: adaptiveavgpool1d
        kwargs:
          output_size: 5000
        id: adaptivepool
      - name: BatchNorm1d
        kwargs:
          num_features: 1
        id: bn0
      - name: Conv1d
        kwargs:
          in_channels: 1
          out_channels: 23
          kernel_size: 18
          dilation: 3
          padding: 9
        id: conv1
      - name: relu
      - name: avgpool1d
        kwargs:
          kernel_size: 3
        id: avgpool1

      - name: BatchNorm1d
        kwargs:
          num_features: 23
        id: bn1

      - name: Conv1d
        kwargs:
          in_channels: 23
          out_channels: 28
          kernel_size: 74
          dilation: 3
          padding: 37
          bias: False
        id: conv2
      - name: Relu
      - name: avgpool1d
        kwargs:
          kernel_size: 3
        id: avgpool2

      - name: BatchNorm1d
        kwargs:
          num_features: 28
        id: bn2
      - name: Conv1d
        kwargs:
          in_channels: 28
          out_channels: 54
          kernel_size: 44
          padding: 22
          dilation: 3
          bias: False
        id: conv3
      - name: Relu
      - name: AvgPool1d
        kwargs:
          kernel_size: 3
        id: avgpool3

      - name: BatchNorm1d
        kwargs:
          num_features: 54
        id: bn3
      - name: Conv1d
        kwargs:
          in_channels: 54
          out_channels: 59
          kernel_size: 68
          padding: 34
          dilation: 3
          bias: False
        id: conv4
      - name: Relu
      - name: avgpool1d
        kwargs:
          kernel_size: 3
        id: avgpool
      - name: Flatten
        kwargs:
          start_dim: 1
      - name: Linear
        kwargs:
          in_features: 118
          out_features: 416
        id: linear1
      - name: dropout
        kwargs:
          p: 0.2
      - name: Relu
      - name: Linear
        kwargs:
          in_features: 416
          out_features: 6
        id: linear2

classes:
  - IL  # Inadecuate lubrication
  - CD  # Corosion damage
  - EL  # Exceeding life
  - CL  # Contaminated lubricant
  - OS  # Overload Stress
  - NEW  # New bearing

training_params:
  epoch_num: 70
  dataloader_params:
    batch_size: 256
  optimizer_params:
    class: adamw
    kwargs:
      lr: 0.00019
      weight_decay: 0.1656
  scheduler_params:
    class: cosine
    kwargs:
      T_max: 70




eval_params:
  batch_size: 256


