


model:
  class: CNN
  kwargs:
    layers:
      - name: BatchNorm1d
        kwargs:
          num_features: 1
        id: bn0
      - name: Conv1d
        kwargs:
          in_channels: 1
          out_channels: 8
          kernel_size: 30
        id: conv1
      - name: relu
      - name: avgpool1d
        kwargs:
          kernel_size: 5
        id: avgpool1

      - name: BatchNorm1d
        kwargs:
          num_features: 8
        id: bn1

      - name: Conv1d
        kwargs:
          in_channels: 8
          out_channels: 16
          kernel_size: 24
          bias: False
        id: conv2
      - name: Relu
      - name: avgpool1d
        kwargs:
          kernel_size: 5
        id: avgpool2

      - name: BatchNorm1d
        kwargs:
          num_features: 16
        id: bn2
      - name: Conv1d
        kwargs:
          in_channels: 16
          out_channels: 32
          kernel_size: 16
          bias: False
        id: conv3
      - name: Relu
      - name: AvgPool1d
        kwargs:
          kernel_size: 5
        id: avgpool3

      - name: BatchNorm1d
        kwargs:
          num_features: 32
        id: bn3
      - name: Conv1d
        kwargs:
          in_channels: 32
          out_channels: 64
          kernel_size: 11
          bias: False
        id: conv4
      - name: Relu
      - name: avgpool1d
        kwargs:
          kernel_size: 15
        id: avgpool
      - name: Flatten
        kwargs:
          start_dim: 1
      - name: Linear
        kwargs:
          in_features: 960
          out_features: 630
        id: linear1
      - name: dropout
        kwargs:
          p: 0.41
      - name: Relu
      - name: Linear
        kwargs:
          in_features: 630
          out_features: 6
        id: linear2

classes:
  0: Inadequate Lubrication
  1: Corrosion Damage
  2: Exceeding Life
  3: Contaminated Lubricant
  4: Overload Stress
  5: New

training_params:
  epoch_num: 150
  dataloader_params:
    batch_size: 512
  optimizer_params:
    class: adamw
    kwargs:
      lr: 0.0002297
      weight_decay: 0.04780
  scheduler_params:
    class: cosine
    kwargs:
      T_max: 150




eval_params:
  batch_size: 512


