
model:
  class: CNN_spec
  kwargs:
    layers:
      # spectrogram
      - name: spectrogram
        kwargs:
          n_fft: 512
        id: spectrogram

      # first conv block
      - name: Conv2d
        kwargs:
          in_channels: 1
          out_channels: 16
          kernel_size: 15
          padding: 2
          bias: True
        id: conv1

      - name: Relu

      - name: BatchNorm2d
        kwargs:
          num_features: 16
        id: bn1

      # second conv block
      - name: Conv2d
        kwargs:
          in_channels: 16
          out_channels: 32
          kernel_size: 3
          padding: 1
          bias: True
        id: conv2

      - name: Relu

      - name: BatchNorm2d
        kwargs:
          num_features: 32
        id: bn2

      # third conv block
      - name: Conv2d
        kwargs:
          in_channels: 32
          out_channels: 32
          kernel_size: 3
          padding: 1
          bias: True
        id: conv3

      - name: Relu

      - name: BatchNorm2d
        kwargs:
          num_features: 32
        id: bn3

      # forth conv block
      - name: Conv2d
        kwargs:
          in_channels: 32
          out_channels: 64
          kernel_size: 5
          padding: 2
          bias: True
        id: conv4

      - name: Relu

      - name: BatchNorm2d
        kwargs:
          num_features: 64
        id: bn4

      - name: adaptiveavgpool2d
        kwargs:
          output_size: 6
        id: adaptivepool

      - name: Flatten
        kwargs:
          start_dim: 1



      - name: Linear
        kwargs:
          in_features: 2304
          out_features: 1000
        id: linear1
      - name: Relu

      - name: Linear
        kwargs:
          in_features: 1000
          out_features: 6
        id: linear2


classes:
  - IL  # Inadecuate lubrication
  - CD  # Corosion damage
  - EL  # Exceeding life
  - CL  # Contaminated lubricant
  - OS  # Overload Stress
  - NEW  # New bearing

training_params:
  epoch_num: 16

  dataloader_params:
    batch_size: 128
  optimizer_params:
    class: adam
    kwargs:
      lr: 0.01
  scheduler_params:
    class: exponential
    kwargs:
      gamma: 0.8


eval_params:
  batch_size: 32
