
model:
  class: Inception time
  kwargs:
    layers:
      - name: Batchnorm1d
        kwargs:
          num_features: 1

      - name: InceptionBlock
        kwargs:
          in_channels: 1
          bottleneck_channels: 12
          n_filters: 8
          kernel_sizes: [13, 31, 61]
          use_residual: True
        id: inceptionblock1

      - name: InceptionBlock
        kwargs:
          in_channels: 16 # n_filters x 4
          bottleneck_channels: 3
          n_filters: 9
          kernel_sizes: [13, 23, 59]
          use_residual: True
        id: inceptionblock2

      - name: AdaptiveAvgPool1d
        kwargs:
          output_size: 11
        id: adaptivepool
      - name: Flatten
        kwargs:
          start_dim: 1
      - name: Linear
        kwargs:
          in_features: 311 # outputsize of adaptivep x n_filters x 4
          out_features: 64
        id: linear1

      - name: relu
      - name: Linear
        kwargs:
          in_features: 64
          out_features: 6
        id: linear2


classes:
  0: Inadequate Lubrication
  1: Corrosion Damage
  2: Exceeding Life
  3: Contaminated Lubricant
  4: Overload Stress
  5: New


training_params:
  epoch_num: 13

  dataloader_params:
    batch_size: 128

  optimizer_params:
    class: adamw
    kwargs:
      lr: 0.001445
  scheduler_params:
    class: warmups
    kwargs:
      T_0: 6



eval_params:
  batch_size: 256





