
in_channels: 240
activation: ReLU



model:
  type : Inception time
  kwargs:
    layers:
      - name: InceptionBlock
        kwargs:
          in_channels: 1
          bottleneck_channels: 4
          n_filters: 15
          kernel_sizes: [17, 65, 131]
          use_residual: True
        id: inceptionblock1

      - name: InceptionBlock
        kwargs:
          in_channels: 60 # n_filters x 4
          bottleneck_channels: 48
          n_filters: 25
          kernel_sizes: [17, 65, 131]
          use_residual: True
        id: inceptionblock2

      - name: AdaptiveAvgPool1d
        kwargs:
          output_size: 12
        id: adaptivepool
      - name: Flatten
        kwargs:
          start_dim: 1
      - name: Linear
        kwargs:
          in_features: 1200 # outputsize of adaptivep x n_filters x 4
          out_features: 300
        id: linear1
      - name: relu
      - name: Linear
        kwargs:
          in_features: 300
          out_features: 6
        id: linear2

training_params:
  epoch_num: 7
  lr: 0.0018
  warmups: 1
  dataloader_params:
    batch_size: 32


eval_params:
  batch_size: 32


# TODO: RENAME USE GPT
tensorboard_log_frequency:
  validation_loss: 128
  accuracy: 128
  confusion_matrix: 128



