


model:
  type: LSTM
  kwargs:
    layers:
      lstm_config:
        - name: LSTM
          kwargs:
            input_size: 8500
            hidden_size: 512
            num_layers: 2
            batch_first: True
            bidirectional: True
          id: lstm
      output_config:
        - name: Linear
          kwargs:
            in_features: 1024
            out_features: 512
          id: linear1
        - name: dropout
          kwargs:
            p: 0.2
          id: dropout
        - name: relu
        - name: Linear
          kwargs:
            in_features: 512
            out_features: 6
          id: linear2

tensorboard_log_frequency:
  validation_loss: 256
  accuracy: 256
  confusion_matrix: 256



training_params:
  lr: 0.0005
  epoch_num: 20
  warmups: 1
  dataloader_params:
    batch_size: 64

eval_params:
  batch_size: 256

