
model:
  class: LSTM
  kwargs:
    layers:
      bn_config:
        - name: batchnorm1d
          kwargs:
            num_features: 1
          id: bn
        - name: adaptiveavgpool1d
          kwargs:
            output_size: 5000
          id: adaptivepool

      lstm_config:
        - name: LSTM
          kwargs:
            input_size: 100
            hidden_size: 156
            num_layers: 3
            batch_first: True
            dropout: 0.4456
            bidirectional: True
          id: lstm
      output_config:
        - name: Linear
          kwargs:
            in_features: 312
            out_features: 19
          id: linear1
        - name: relu
        - name: flatten
        - name: Linear
          kwargs:
            in_features: 950
            out_features: 6
          id: linear2

# use acronyms
classes:
  - IL  # Inadecuate lubrication
  - CD  # Corosion damage
  - EL  # Exceeding life
  - CL  # Contaminated lubricant
  - OS  # Overload Stress
  - NEW  # New bearing



training_params:
  epoch_num: 80
  dataloader_params:
    batch_size: 256
  optimizer_params:
    class: adamw
    kwargs:
      lr: 0.00309
      weight_decay: 0.098
  scheduler_params:
    class: cosine
    kwargs:
      T_max: 80

eval_params:
  batch_size: 256

