
model:
  class: Inception time
  kwargs:
    layers:
      - name: Batchnorm1d
        kwargs:
          num_features: 1
      - name: adaptiveavgpool1d
        kwargs:
          output_size: 1000
        id: adaptpool1
      - name: InceptionBlock
        kwargs:
          in_channels: 1
          bottleneck_channels: 10
          n_filters: 9
          kernel_sizes: [51, 71, 191]
          use_residual: True
        id: inceptionblock1
      - name: relu
      - name: InceptionBlock
        kwargs:
          in_channels: 36 # n_filters x 4
          bottleneck_channels: 10
          n_filters: 9
          kernel_sizes: [51, 71, 191]
          use_residual: True
        id: inceptionblock2

      - name: avgpool1d
        kwargs:
          kernel_size: 50

      - name: Flatten
        kwargs:
          start_dim: 1
      - name: Linear
        kwargs:
          in_features: 720 # outputsize of adaptivep x n_filters x 4
          out_features: 242
        id: linear1
      - name: dropout
        kwargs:
          p: 0.484
      - name: relu
      - name: Linear
        kwargs:
          in_features: 242
          out_features: 6
        id: linear2


classes:
  - IL  # Inadecuate lubrication
  - CD  # Corosion damage
  - EL  # Exceeding life
  - CL  # Contaminated lubricant
  - OS  # Overload Stress
  - NEW  # New bearing


training_params:
  epoch_num: 90

  dataloader_params:
    batch_size: 256

  optimizer_params:
    class: adamw
    kwargs:
      lr: 0.0007
      weight_decay: 0.02688
  scheduler_params:
    class: cosine
    kwargs:
      T_max: 90



eval_params:
  batch_size: 256





