
lr: 0.0001


model:
  class: CNN
  kwargs:
    layers:
      - name: Conv1d
        kwargs:
          in_channels: 1
          out_channels: 8
          kernel_size: 100
      - name: Conv1d
        kwargs:
          in_channels: 8
          out_channels: 16
          kernel_size: 100
      - name: BatchNorm1d
        kwargs:
          num_features: 16
      - name: AdaptiveAvgPool1d
        kwargs:
          output_size: 1000
      - name: Flatten
        kwargs:
          start_dim: 1

      - name: Linear
        kwargs:
          in_features: 1000
          out_features: 9



training_params:
  epoch_num: 10
  dataloader_params:
    batch_size: 256
    shuffle: true

eval_params:
  batch_size: 256
  shuffle: true



