
lr: 0.001


model:
  type: CNN
  kwargs:
    conv_layers:
      - name: Conv1d
        kwargs:
          in_channels: 1
          out_channels: 1
          kernel_size: 100

    layers:
      - name: Linear
        kwargs:
            in_features: 1000
            out_features: 9
      - name: Linear
        kwargs:
            in_features: 1000
            out_features: 9



training_params:
  epoch_num: 2
  dataloader_params:
    batch_size: 64
    shuffle: true

eval_params:
  batch_size: 64
  shuffle: true



