
in_channels: 240
activation: ReLU
lr: 0.001
bottleneck_channels: 32

model:
  type : Inception time
  kwargs:
    layers:
      - name: InceptionBlock
        kwargs:
          in_channels: 1
          n_filters: 32
          kernel_sizes: [11, 23, 41]
          bottleneck_channels: 32
          use_residual: True
      - name: InceptionBlock
        kwargs:
          in_channels: 128
          n_filters: 32
          kernel_sizes: [11, 23, 41]
          bottleneck_channels: 32
          use_residual: True
      - name: AdaptiveAvgPool1d
        kwargs:
          output_size: 1
      - name: Flatten
        kwargs:
          start_dim: 1
      - name: Linear
        kwargs:
          in_features: 128
          out_features: 9

training_params:
  epoch_num: 1
  dataloader_params:
    batch_size: 256
    shuffle: true

eval_params:
  batch_size: 256
  shuffle: true

# TODO: RENAME
tensorboard_params:
  validation_loss: 256
  classification_report: 256
  confusion_matrix: 256

bottleneck:
  - name: Conv1d
    kwargs:
      in_channels:
      out_channels:
      kernel_size: 1
      bias: False


