
in_channels: 240
activation: ReLU
lr: 0.001
bottleneck_channels: 32
training_params:
  epoch_num: 2
  dataloader_params:
    batch_size: 128
    shuffle: true

eval_params:
  batch_size: 128
  shuffle: true

bottleneck:
  - name: Conv1d
    kwargs:
      in_channels:
      out_channels:
      kernel_size: 1
      bias: False


layers:
  - name: InceptionBlock
    kwargs:
      in_channels: 1
      n_filters: 32
      kernel_sizes: [5, 11, 23]
      bottleneck_channels: 32
      use_residual: True
  - name: InceptionBlock
    kwargs:
      in_channels: 128
      n_filters: 32
      kernel_sizes: [5, 11, 23]
      bottleneck_channels: 32
      use_residual: True
