
in_channels: 240
activation: ReLU
lr: 0.001
bottleneck_channels: 32

model:
  class: Inception time
  kwargs:
    layers:
      - name: InceptionBlock
        kwargs:
          in_channels: 1
          n_filters: 32
          kernel_sizes: [11, 23, 41]
          bottleneck_channels: 32
          use_residual: True
      - name: InceptionBlock
        kwargs:
          in_channels: 128
          n_filters: 32
          kernel_sizes: [11, 23, 41]
          bottleneck_channels: 32
          use_residual: True

training_params:
  epoch_num: 4
  dataloader_params:
    batch_size: 256
    shuffle: true

eval_params:
  batch_size: 256
  shuffle: true

bottleneck:
  - name: Conv1d
    kwargs:
      in_channels:
      out_channels:
      kernel_size: 1
      bias: False


