
lr: 0.001

model:
  type: LSTM
  attention: False
  kwargs:
    lstm_config:
      - name: LSTM
        kwargs:
          input_size: 1000
          hidden_size: 512
          num_layers: 2
          batch_first: True
          bidirectional: True
    output_config:
      - name: Linear
        kwargs:
          in_features: 1024
          out_features: 9

tensorboard_params:
  validation_loss: 50
  classification_report: 100
  confusion_matrix: 200


training_params:
  epoch_num: 20
  dataloader_params:
    batch_size: 256
    shuffle: true

eval_params:
  batch_size: 256
  shuffle: false

