
lr: 0.001

training_params:
  epoch_num: 10
  dataloader_params:
    batch_size: 32
    shuffle: true

eval_params:
  batch_size: 32
  shuffle: true

layers:
  - name: LSTM
    kwargs:
      input_size: 240
      hidden_size: 64
      num_layers: 2
      batch_first: True
  - name: Linear
    kwargs:
      in_features: 128
      out_features: 1