model:
  type: lstm_fcn
  attention: False
  kwargs:
    in_channels: 1
    layers:
      lstm_config:
        - name: LSTM
          kwargs:
            input_size: 1000
            hidden_size: 1600
            num_layers: 2
            batch_first: True
            bidirectional: True
            dropout: 0.5
      fcn_config:
        - name: Conv1d
          kwargs:
            in_channels: 1
            out_channels: 16
            kernel_size: 100
        - name: BatchNorm1d
          kwargs:
            num_features: 16
        - name: Relu
        - name: Conv1d
          kwargs:
            in_channels: 16
            out_channels: 32
            kernel_size: 100
        - name: BatchNorm1d
          kwargs:
            num_features: 32
        - name: AvgPool1d
          kwargs:
            kernel_size: 8
        - name: Relu
      output_config:
        - name: Linear
          kwargs:
            in_features: 6400
            out_features: 2500
        - name: Dropout
          kwargs:
            p: 0.5
        - name: Linear
          kwargs:
            in_features: 2500
            out_features: 100
        - name: Linear
          kwargs:
            in_features: 100
            out_features: 9

lr: 0.000003
# number of batches you write down validation loss, confusion_matrix, etc.
tensorboard_params:
  validation_loss: 512
  accuracy: 1024
  confusion_matrix: 1024

training_params:
  epoch_num: 10
  dataloader_params:
    batch_size: 1024
    shuffle: true

eval_params:
  batch_size: 512
  shuffle: false

