
lr: 0.01
model:
  type: MLP
  kwargs:
    layers:
        - name: Linear
          kwargs:
            in_features: 2000
            out_features: 1000
        - name: Linear
          kwargs:
            in_features: 1000
            out_features: 100
        - name: Linear
          kwargs:
            in_features: 100
            out_features: 9

training_params:
  epoch_num: 100
  dataloader_params:
    batch_size: 500
    shuffle: true

eval_params:
  batch_size: 500
  shuffle: true

