
lr: 0.01
model:
  class: MLP
  kwargs:

    layers_branch1:
      - name: Linear
        args: [ 1000, 2000 ]
      - name: Linear
        args: [ 2000, 500 ]
      - name: Linear
        args: [ 500, 9 ]
    layers_branch2:

training_params:
  epoch_num: 100
  dataloader_params:
    batch_size: 500
    shuffle: true

eval_params:
  batch_size: 500
  shuffle: true

